name: Variables Practice

on:
  push:
    branches:
      - main

env:
  MY_NAME: Vinod
  ENVIRONMENT: DEV

jobs:
  variables:
    runs-on: ubuntu-latest

    steps:
      - name: Show variables
        run: |
          echo "My name is $MY_NAME"
          echo "Environment is $ENVIRONMENT"
          echo "App name is ${{ vars.APP_NAME }}"
